runtime: nodejs18

env_variables:
  # Application
NAME: 'api-autenticacao'
VERSION: '1.0.0'
NODE_ENV: 'develop'

# DATABASE
DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}

# FIREBASE
API_KEY: ${API_KEY}
AUTH_DOMAIN: ${AUTH_DOMAIN}
PROJECT_ID: ${PROJECT_ID}
STORAGE_BUCKET: ${STORAGE_BUCKET}
MESSAGING_SENDER_ID: ${MESSAGING_SENDER_ID}
APP_ID: ${APP_ID}
MEASUREMENT_ID: ${MEASUREMENT_ID}